name: Evolene CI

on:
  schedule:
    - cron: "0 1 1 * *"

  push:
    paths-ignore:
          - '*.md'
          - '*.png'
  workflow_dispatch:

jobs:
  Evolene:
    name: Continuous Integration
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Run Evolene CI pipeline steps
        shell: bash
        env:
          SLACK_CHANNELS: "#team-pipeline-build"
          BUILD_INFORMATION_OUTPUT_FILE: "/version.js"
          PUSH_PUBLIC: True
          SKIP_DRY_RUN: True
          EVOLENE_TEST_SECRETS: "${{secrets.EVOLENE_TEST_SECRETS}}"
        run: |
          ${{ secrets.EVOLENE_RUN_COMMAND }}

